
in_root: '/home/ROBARTS/alik/graham' #for cbs server
#in_root: '/home/akhanf' #for graham

#files in one big zip file - these paths are relative to in_root defined above
in_agg_zip: 
  snakebatch_dwi:
    HCP: 'projects/ctb-akhanf/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip'
    LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_2024_03_19.zip'
  snakebatch:
    HCP: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_HCP_snakeanat_fmriprep_2024_03_21.zip'
    LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_2024_03_19.zip'

in_demog_tabular:
  HCP: 'projects/ctb-akhanf/ext-data/hcp_development/HCPDevImagingManifestBeh/ndar_subject01.txt'


  

#to find paths below, use: unzip -l cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip | less
input_path: 
  dwi_nii: 'snakebatch_dwi/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-eddy_dwi.nii.gz'
  dwi_mask: 'snakebatch_dwi/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-brain_mask.nii.gz'
  bold_nii:     
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-preproc_bold.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-preproc_bold.nii.gz'
  bold_json: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-preproc_bold.json'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-preproc_bold.json'
  bold_confounds: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_desc-confounds_timeseries.tsv'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_desc-confounds_timeseries.tsv'
  bold_mask: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-brain_mask.nii.gz'
  t1_mask:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_desc-brain_mask.nii.gz'
  surf_gii_t1: 'snakebatch/{dataset}/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/T1w/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  surf_gii_mni: 'snakebatch/{dataset}/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/MNINonLinear/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  hippunfold_vol_tsv: 'snakebatch/{dataset}/derivatives/hippunfold/hippunfold/sub-{subject}/anat/sub-{subject}_space-cropT1w_desc-subfields_atlas-bigbrain_volumes.tsv'



#this is the output folder
root: results

subj_wildcards:
  subject: '{subject}'


datasets:
  - HCP
  - LOBE

subjects: 
  HCP:
   - 'HCD0277447'
  LOBE:
   - '007'

template_surf: 'resources/tpl-fsLR/tpl-fsLR_den-32k_hemi-{hemi}_{surf}.surf.gii'

atlas:
  schaefer: resources/schaefer_2018/Schaefer2018_300Parcels_7Networks_order.dlabel.nii
  mmp: resources/mmp/Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii
  brainnetome: resources/brainnetome/fsaverage.BN_Atlas.32k_fs_LR_updated.dlabel.nii
dwi:
  shells: 
    - '0'
    - '1500'
    - '3000'

  lmax: 
    - '0'
    - '8'
    - '8'

  sl_count: 10000

 
func:

  fwhm:
    - 5
  

  task:
    - rest

  parcellation:    
    do_exclude_outliers: False
    n_stdevs_exclude: 2

  correlation:
    do_fisher_z: False
  denoise:
    24HMP8PhysSpikeReg:
      clean_img_opts:
        standardize: True
        detrend: False
        low_pass: 0.08
        high_pass: 0.01
      confounds_name:
        - csf 
        - csf_derivative1 
        - csf_derivative1_power2
        - csf_power2 
      confounds_like:
        - white_matter
        - trans
        - rot
        - motion_outlier
        - steady_state_outlier





singularity:
  mrtrix: 'docker://mrtrix3/mrtrix3:3.0.4'
  diffparc: 'docker://khanlab/diffparc-deps:v0.1.0-fix'  

