
in_root: '$HOME/graham' #for cbs server
#in_root: '$HOME' #for graham

groups:
  dre: 'dre_first_scan == 1'
  nondre: 'dre_first_scan == 0'

coltypes:
  - NSFC
  - NFC
  - NSC

ttests:
  - group1: dre
    group2: nondre

 # - group1: tle
 #   group2: nontle
#  - group1: motor_focal_seizures
#    group2: non-motor_focal_seizures	
#  - group1: generalized_seizures
#    group2: non-generalized_seizures    
#  - group1: FTBTC
#    group2: no_FTBTC    
#  - group1: dre_first_scan	
#    group2: no_dre_first_scan    
#  - group1: lat_eeg_left
#    group2: no_lat_eeg_left
#  - group1: lat_eeg_right
#    group2: no_lat_eeg_right
#  - group1: lat_seeg_left
#    group2: no_lat_seeg_left    
#  - group1: lat_seeg_right        
#    group2: no_lat_seeg_right    
#  - group1: lat_mri_left
#    group2: no_lat_mri_left
#  - group1: lat_mri_right              
#    group2: no_lat_mri_right    
    
    
    
#lat_pet_left	lat_pet_right	lat_semiology_left	lat_semiology_right	lat_final_left	lat_final_right	lat_final_bilateral	lat_final_multifocal	loc_eeg_frontal	loc_eeg_occipital	loc_eeg_parietal	loc_eeg_temporal	loc_mri_frontal	loc_mri_occipital	loc_mri_parietal	loc_mri_temporal	loc_pet_frontal	loc_pet_occipital	loc_pet_parietal	loc_pet_temporal	loc_semiology	loc_final_frontal	loc_final_occipital	loc_final_parietal	loc_final_temporal	loc_final_temporal_plus	loc_final_extratemporal



#files in one big zip file - these paths are relative to in_root defined above
in_agg_zip: 
  snakebatch_dwi:
    HCP: 'projects/ctb-akhanf/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip'
    LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_2024_03_19.zip'
  snakebatch:
    HCP: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_HCP_snakeanat_fmriprep_2024_03_21.zip'
    LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_2024_03_19.zip'

in_tabular:
  HCP: 'projects/ctb-akhanf/ext-data/hcp_development/HCPDevImagingManifestBeh/ndar_subject01.txt'
  LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/raw/baseline/clinical/participants.tsv' #<-- have this point to most up-to-date clinical data

  

#to find paths below, use: unzip -l cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip | less
input_path: 
  dwi_nii: 'snakebatch_dwi/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-eddy_dwi.nii.gz'
  dwi_mask: 'snakebatch_dwi/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-brain_mask.nii.gz'
  bold_nii:     
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-preproc_bold.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-preproc_bold.nii.gz'
  bold_json: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-preproc_bold.json'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-preproc_bold.json'
  bold_confounds: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_desc-confounds_timeseries.tsv'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_desc-confounds_timeseries.tsv'
  bold_mask: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-brain_mask.nii.gz'
  t1_mask:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_desc-brain_mask.nii.gz'
  surf_gii_t1: 'snakebatch/{dataset}/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/T1w/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  surf_gii_mni: 'snakebatch/{dataset}/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/MNINonLinear/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  hippunfold_vol_tsv: 'snakebatch/{dataset}/derivatives/hippunfold/hippunfold/sub-{subject}/anat/sub-{subject}_space-cropT1w_desc-subfields_atlas-bigbrain_volumes.tsv'



#this is the output folder
root: results

subj_wildcards:
  subject: '{subject}'


datasets:
  - HCP
  - LOBE

use_test_subjects: True

test_subjects: 
  HCP:
   - 'HCD0277447'
   - 'HCD0021614'
   - 'HCD0026119'

  LOBE:
   - '007'
   - '009'
   - '010'

template_surf: 'resources/tpl-fsLR/tpl-fsLR_den-32k_hemi-{hemi}_{surf}.surf.gii'

#atlases to actually use:
atlases:
  - schaefer


atlas:
  schaefer: 
    dlabel: resources/schaefer_2018/Schaefer2018_300Parcels_7Networks_order.dlabel.nii
    network_pattern: '[^_]+_[^_]+_([^_]+)' #regex to find network name within label
  mmp: 
    dlabel: resources/mmp/Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii
  brainnetome: 
    dlabel: resources/brainnetome/fsaverage.BN_Atlas.32k_fs_LR_updated.dlabel.nii
dwi:
  shells: 
    - '0'
    - '1500'
    - '3000'

  lmax: 
    - '0'
    - '8'
    - '8'

  sl_count: 1000000

 
func:

  fwhm:
    - 5
  

  task:
    - rest

  parcellation:    
    do_exclude_outliers: False
    n_stdevs_exclude: 2

  correlation:
    do_fisher_z: False
  denoise:
    24HMP8PhysSpikeReg:
      clean_img_opts:
        standardize: True
        detrend: False
        low_pass: 0.08
        high_pass: 0.01
      confounds_name:
        - csf 
        - csf_derivative1 
        - csf_derivative1_power2
        - csf_power2 
      confounds_like:
        - white_matter
        - trans
        - rot
        - motion_outlier
        - steady_state_outlier


nichord:
  struc:
    edge_widthscale: 0.001
  func:
    edge_widthscale: 0.001

netplotbrain:
  struc:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 100
    edge_widthscale: 0.001


  func:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 0.9
    edge_widthscale: 0.3


singularity:
  mrtrix: 'docker://mrtrix3/mrtrix3:3.0.4'
  diffparc: 'docker://khanlab/diffparc-deps:v0.1.0-fix'  

