
#files in one big zip file
in_agg_zip: 
  snakebatch: '/home/ROBARTS/alik/graham/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip'

in_subj_zip:
  freesurfer: '/path/to/freesurfer/sub-{subject}_freesurfer.zip'  

#to find paths below, use: unzip -l /home/ROBARTS/alik/graham/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip | less
input_path: 
  dwi_nii: 'snakebatch/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-eddy_dwi.nii.gz'
  dwi_mask: 'snakebatch/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-brain_mask.nii.gz'
  bold_nii:     
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz'
  bold_json: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-MNI152NLin2009cAsym_desc-preproc_bold.json'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.json'
  bold_confounds: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_desc-confounds_timeseries.tsv'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_desc-confounds_timeseries.tsv'
  bold_mask: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz'
  t1_mask:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_desc-brain_mask.nii.gz'
  surf_gii_t1: 'snakebatch/{dataset}/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/T1w/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  surf_gii_mni: 'snakebatch/{dataset}/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/MNINonLinear/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  hippunfold_vol_tsv: 'snakebatch/{dataset}/derivatives/hippunfold/hippunfold/sub-{subject}/anat/sub-{subject}_space-cropT1w_desc-subfields_atlas-bigbrain_volumes.tsv'

  #NOTE: the MNINonLinear space for cifti files is MNI152NLin6Asym, whereas the fmriprep preproc bold is in MNI152NLin2009cAsym -- should include the MNI152NLin6Asym space when running fmriprep next time (as well as T1w)


root: results

subj_wildcards:
  subject: '{subject}'


datasets:
  - HCP
  - LOBE

subjects: 
  HCP:
   - 'HCD0277447'
  LOBE:
   - '007'

atlas:
  schaefer: resources/schaefer_2018/Schaefer2018_300Parcels_7Networks_order.dlabel.nii
  mmp: resources/mpm/Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii
  brainnetome: resources/brainnetome/fsaverage.BN_Atlas.32k_fs_LR_updated.dlabel.nii
dwi:
  shells: 
    - '0'
    - '1500'
    - '3000'

  lmax: 
    - '0'
    - '8'
    - '8'

  sl_count: 10000

 
func:

  fwhm:
    - 5
  
  space:
    - MNI152NLin2009cAsym

  task:
    - rest

  parcellation:    
    do_exclude_outliers: False
    n_stdevs_exclude: 2

  correlation:
    do_fisher_z: False
  denoise:
    24HMP8PhysSpikeReg:
      clean_img_opts:
        standardize: True
        detrend: False
        low_pass: 0.08
        high_pass: 0.01
      confounds_name:
        - csf 
        - csf_derivative1 
        - csf_derivative1_power2
        - csf_power2 
      confounds_like:
        - white_matter
        - trans
        - rot
        - motion_outlier
        - steady_state_outlier





singularity:
  mrtrix: 'docker://mrtrix3/mrtrix3:3.0.4'

