#in_root: '$HOME' #for narval
in_root: '$HOME/beluga' #for cbs server
#in_root: '$HOME' #for graham

groups:
  dre: 'dre_first_scan == 1'
  nondre: 'dre_first_scan == 0'
  lobe: dataset == 'LOBE'
  hcp: dataset == 'HCP'
  female: sex == 'F'
  male: sex == 'M'
  seizure_onset_below_5: 'age_seizure_onset <= 5'
  seizure_onset_5_and_up: 'age_seizure_onset > 5'
  ep_diagnosis_age_below_9: 'age_ep_diagnosis <= 8'
  ep_diagnosis_age_above_8: 'age_ep_diagnosis >8'
  motor_seizures: 'motor_focal_seizures == 1'
  nonmotor_seizures: 'non-motor_focal_seizures == 1'
  generalized: 'generalized_seizures == 1'
  nongeneralized: 'generalized_seizures == 0'
  FTBTC: 'FTBTC == 1'
  nonFTBTC: 'FTBTC == 0'
  high_asm: 'asm_first_scan >= 3'
  low_asm: 'asm_first_scan < 3'
  frontal: 'loc_final_frontal == 1'
  nonfrontal: 'loc_final_frontal == 0'
  temporal: 'loc_final_temporal == 1'
  nontemporal: 'loc_final_temporal == 0'
  occipital: 'loc_final_occipital == 1'
  nonoccipital: 'loc_final_occipital == 0'
  parietal: 'loc_final_parietal == 1'
  nonparietal: 'loc_final_parietal == 0'
  temporal_plus: 'loc_final_temporal_plus == 1'
  nontemporal_plus: 'loc_final_temporal_plus == 0'
  left: 'lat_final_left == 1'
  nonleft: 'lat_final_left == 0'
  right: 'lat_final_right == 1'
  nonright: 'lat_final_right == 0'
  bilateral: 'lat_final_bilateral == 1'
  nonbilateral: 'lat_final_bilateral == 0'
  multifocal: 'lat_final_multifocal == 1'
  nonmultifocal: 'lat_final_multifocal == 0'

coltypes:
  - NSFC
  - NFC
  - NSC
  - RSFC
  - RFC
  - RSC

ttests:
  - group1: dre
    group2: nondre
  - group1: temporal
    group2: nontemporal
  - group1: motor_seizures
    group2: nonmotor_seizures
  - group1: generalized
    group2: nongeneralized
  - group1: FTBTC
    group2: nonFTBTC
  - group1: left
    group2: nonleft
  - group1: right
    group2: nonright
  - group1: male
    group2: female
  - group1: lobe
    group2: hcp
  - group1: seizure_onset_below_5
    group2: seizure_onset_5_and_up
  - group1: ep_diagnosis_age_below_9
    group2: ep_diagnosis_age_above_8
  - group1: high_asm
    group2: low_asm
  - group1: frontal
    group2: nonfrontal
  - group1: occipital
    group2: nonoccipital
  - group1: parietal
    group2: nonparietal
  - group1: temporal_plus
    group2: nontemporal_plus
  - group1: bilateral
    group2: nonbilateral
  - group1: multifocal
    group2: nonmultifocal



#lat_pet_left	lat_pet_right	lat_semiology_left	lat_semiology_right	lat_final_left	lat_final_right	lat_final_bilateral	lat_final_multifocal	loc_eeg_frontal	loc_eeg_occipital	loc_eeg_parietal	loc_eeg_temporal	loc_mri_frontal	loc_mri_occipital	loc_mri_parietal	loc_mri_temporal	loc_pet_frontal	loc_pet_occipital	loc_pet_parietal	loc_pet_temporal	loc_semiology	loc_final_frontal	loc_final_occipital	loc_final_parietal	loc_final_temporal	loc_final_temporal_plus	loc_final_extratemporal



#files in one big zip file - these paths are relative to in_root defined above
in_agg_zip: 
  snakebatch_dwi:
    HCP: 'scratch/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip'
    LOBE: 'scratch/derivatives/snakebatch_LOBE_2024_03_19.zip'
  snakebatch:
    HCP: 'scratch/derivatives/snakebatch_HCP_snakeanat_fmriprep_2024_03_21.zip'
    LOBE: 'scratch/derivatives/snakebatch_LOBE_2024_03_19.zip'

in_tabular:
  HCP: 'projects/ctb-akhanf/ext-data/hcp_development/HCPDevImagingManifestBeh/ndar_subject01.txt'
  LOBE: 'scratch/raw/baseline/clinical/participants.tsv' #<-- have this point to most up-to-date clinical data

  #LOBE: '/lustre04/scratch/mtayl84/raw/baseline/clinical/participants.tsv' #<-- have this point to most up-to-date clinical data

#to find paths below, use: unzip -l cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip | less
input_path: 
  dwi_nii: 'snakebatch_dwi/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-eddy_dwi.nii.gz'
  dwi_mask: 'snakebatch_dwi/{dataset}/derivatives/snakedwi/snakedwi/sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-brain_mask.nii.gz'
  bold_nii:     
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-preproc_bold.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-preproc_bold.nii.gz'
  bold_json: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-preproc_bold.json'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-preproc_bold.json'
  bold_confounds: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_desc-confounds_timeseries.tsv'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_desc-confounds_timeseries.tsv'
  bold_mask: 
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-T1w_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-T1w_desc-brain_mask.nii.gz'
  t1_mask:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_desc-brain_mask.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_desc-brain_mask.nii.gz'

  t1_surf:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_hemi-{hemi}_{surf}.surf.gii'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_hemi-{hemi}_{surf}.surf.gii'

  msm_sphere:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_hemi-{hemi}_space-fsLR_desc-msmsulc_sphere.surf.gii'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_hemi-{hemi}_space-fsLR_desc-msmsulc_sphere.surf.gii'



  bold_mni:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz'

  bold_mni_ref:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_space-MNI152NLin6Asym_boldref.nii.gz'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-1_space-MNI152NLin6Asym_boldref.nii.gz'

  warp_mni_t1w:
    HCP: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5'
    LOBE: 'snakebatch/{dataset}/derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_acq-MPRvNavAvgEcho12_run-1_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5'

  hippunfold_vol_tsv: 'snakebatch/{dataset}/derivatives/hippunfold/hippunfold/sub-{subject}/anat/sub-{subject}_space-cropT1w_desc-subfields_atlas-bigbrain_volumes.tsv'



#this is the output folder
root: results

subj_wildcards:
  subject: '{subject}'


datasets:
  - HCP
  - LOBE

use_test_subjects: True

test_subjects: 
  HCP: 
     - 'HCD0277447'
  # - 'HCD0021614'
#   - 'HCD0026119'

  LOBE:
    - '007'
#   - '028'
#   - '036'
#   - '040'
    - '041'

template_surf: 'resources/tpl-fsLR/tpl-fsLR_den-32k_hemi-{hemi}_{surf}.surf.gii'
template_fsavg_surf: 'resources/tpl-fsLR/tpl-fsLR_space-fsaverage_hemi-{hemi}_den-32k_{surf}.surf.gii'

#atlases to actually use:
atlases:
  - brainnetome


atlas:
  schaefer: 
    dlabel: resources/schaefer_2018/Schaefer2018_300Parcels_7Networks_order.dlabel.nii
    network_pattern: '[^_]+_[^_]+_([^_]+)' #regex to find network name within label
  mmp: 
    dlabel: resources/mmp/Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii
  brainnetome: 
  #dlabel: resources/brainnetome/fsaverage.BN_Atlas.32k_fs_LR_updated.dlabel.nii
    dlabel: resources/brainnetome/fsaverage.BN_Atlas.32k_fs_LR_updated_withnetworks.dlabel.nii 
    network_pattern: '[^_]+_[^_]+_([^_]+)' #regex to find network name within label
    label_volume: resources/brainnetome/BN_Atlas_246_1mm_subcort_withlabels.nii.gz


cifti:
  structure_label_volume: resources/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_atlas-HCP_dseg_withlabels.nii.gz

dwi:
  shells: 
    - '0'
    - '1500'
    - '3000'

  lmax: 
    - '0'
    - '8'
    - '8'

  sl_count: 1000000

 
func:

  fwhm:
    - 5
  

  task:
    - rest

  parcellation:    
    do_exclude_outliers: False
    n_stdevs_exclude: 2

  correlation:
    do_fisher_z: False
  denoise:
    24HMP8PhysSpikeReg:
      clean_img_opts:
        standardize: True
        detrend: False
        low_pass: 0.08
        high_pass: 0.01
      confounds_name:
        - csf 
        - csf_derivative1 
        - csf_derivative1_power2
        - csf_power2 
      confounds_like:
        - white_matter
        - trans
        - rot
        - motion_outlier
        - steady_state_outlier


nichord:
  struc:
    edge_widthscale: 0.001
  func:
    edge_widthscale: 0.001
  strucFA:
    edge_widthscale: 0.001


netplotbrain:
  struc:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 100
    edge_widthscale: 0.001

  strucFA:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 0.3
    edge_widthscale: 0.5


  func:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 0.9
    edge_widthscale: 0.3


singularity:
  mrtrix: 'docker://mrtrix3/mrtrix3:3.0.4'
  diffparc: 'docker://khanlab/diffparc-deps:v0.1.0-fix'  

